---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - resonite.resonite-operator.pluser.net
  resources:
  - sessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resonite.resonite-operator.pluser.net
  resources:
  - sessions/finalizers
  verbs:
  - update
- apiGroups:
  - resonite.resonite-operator.pluser.net
  resources:
  - sessions/status
  verbs:
  - get
  - patch
  - update
